apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: digit-svd-adm-data-pvc
  namespace: digit
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: localpath
  resources:
    requests:
      storage: 10Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: digit-svd-adm-deployment
  namespace: digit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digit-svd
      component: adm
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: digit-svd
        component: adm
    spec:
      serviceAccountName: digit-svd-sa  # Назначаем новый ServiceAccount
      imagePullSecrets:
        - name: digit-dgepu-secret
      containers:
      - name: adm
        
        image: 85.141.97.224:443/svd_adm:4.8.2.0k
        # imagePullPolicy: Always
        ports:
        - containerPort: 10104
        env:
        - name: SVDCode
          value: "adm"
        - name: SVDControl
          value: "digit-svd-control-service:11000"
        # - name: SVDSocket
        #   value: "10101"
        # - name: EXCHANGE
        #   value: "rest:rest@http://digit-dgepu-service.default.svc.cluster.local/pros"
        - name: TZ
          value: "Europe/Moscow"
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace  # Автоматическое указание текущего namespace
        volumeMounts:
          - name: digit-svd-adm-data-rsc
            mountPath: /svd/host
        # livenessProbe:
        #   exec:
        #     command:
        #     - /bin/sh
        #     - -c
        #     - "exit 0"  # Всегда возвращает успешный статус (код 0)
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        # readinessProbe:
        #   exec:
        #     command:
        #     - /bin/sh
        #     - -c
        #     - "exit 0"  # Всегда возвращает успешный статус (код 0)
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
      volumes:
      - name: digit-svd-adm-data-rsc
        persistentVolumeClaim:
          claimName: digit-svd-adm-data-pvc
        