apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: digit-svd-axikam-data-pvc
  namespace: digit
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: localpath
  resources:
    requests:
      storage: 10Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: digit-svd-axikam-deployment
  namespace: digit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digit-svd
      component: axikam
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: digit-svd
        component: axikam
    spec:
      serviceAccountName: digit-svd-sa  # Назначаем новый ServiceAccount
      imagePullSecrets:
        - name: digit-dgepu-secret
      containers:
      - name: axikam
        
        image: 85.141.97.224:443/svd_axikam:4.8.2.1k
        # imagePullPolicy: Always
        ports:
        - containerPort: 10108
        env:
        - name: SVDCode
          value: "axikam"
        - name: SVDControl
          value: "digit-svd-control-service:11000"
        - name: TZ
          value: "Europe/Moscow"
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace  # Автоматическое указание текущего namespace
        volumeMounts:
          - name: digit-svd-axikam-data-rsc
            mountPath: /svd/host
      volumes:
      - name: digit-svd-axikam-data-rsc
        persistentVolumeClaim:
          claimName: digit-svd-axikam-data-pvc
        