apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: digit-svd-fw-mosgaz-data-pvc
  namespace: digit
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: localpath
  resources:
    requests:
      storage: 10Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: digit-svd-fw-mosgaz-deployment
  namespace: digit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digit-svd
      component: fw-mosgaz
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: digit-svd
        component: fw-mosgaz
    spec:
      serviceAccountName: digit-svd-sa
      imagePullSecrets:
        - name: digit-dgepu-secret
      containers:
      - name: fw-mosgaz
        
        image: 85.141.97.224:443/svd_fw_mosgaz:4.8.1.0k
        ports:
        - containerPort: 10125
        env:
        - name: SVDCode
          value: "fw_mosgaz"
        - name: SVDControl
          value: "digit-svd-control-service:11000"
        - name: TZ
          value: "Europe/Moscow"
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
          - name: digit-svd-fw-mosgaz-data-rsc
            mountPath: /svd/host
      volumes:
      - name: digit-svd-fw-mosgaz-data-rsc
        persistentVolumeClaim:
          claimName: digit-svd-fw-mosgaz-data-pvc
