{
 "title": "DGEPU",
 "description": "Мониторинг производительности ЦИФРА",
 "tags": [
  "ЦИФРА",
  "HTTP",
  "Cassandra",
  "PostgreSQL"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "http_interval", "label": "Интервал HTTP", "query": "10s,30s,1m,2m,5m,10m" },
   {
    "name": "database",
    "label": "Database",
    "query": {
     "query": "label_values({datname=~\"meas_params|pros\"},datname)"
    }
   },
   {
    "name": "cluster",
    "label": "Cassandra Cluster",
    "query": {
     "query": "label_values(cassandra_stats{name=\"java:lang:memory:heapmemoryusage:max\"},cluster)"
    }
   },
   {
    "name": "datacenter",
    "query": {
     "query": "label_values(cassandra_stats{name=\"java:lang:memory:heapmemoryusage:max\"},datacenter)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Базовые метрики", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_uptime_seconds{service=\"digit-dgepu-service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Время последнего запуска",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_start_time_seconds{service=\"digit-dgepu-service\"}*1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Использование Non-Heap",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{service=\"digit-dgepu-service\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{service=\"digit-dgepu-service\", area=\"nonheap\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Использование Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{service=\"digit-dgepu-service\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{service=\"digit-dgepu-service\", area=\"heap\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "График работоспособности приложения",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "sum(up{service=\"digit-dgepu-service\"})",
     "legendFormat": "Работает"
    }
   ]
  },
  {
   "title": "Использование CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_cpu_usage{service=\"digit-dgepu-service\"}",
     "legendFormat": "system"
    },
    {
     "expr": "process_cpu_usage{service=\"digit-dgepu-service\"}",
     "legendFormat": "process"
    },
    {
     "expr": "avg_over_time(process_cpu_usage{service=\"digit-dgepu-service\"}[15m])",
     "legendFormat": "process-15m"
    }
   ]
  },
  { "title": "Мониторинг внешних запросов", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Всего запросов",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(svd_http_counter{service=\"digit-dgepu-service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "График HTTP запросов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "svd_http_counter{service=\"digit-dgepu-service\"}",
     "legendFormat": "Общее количество запросов"
    },
    {
     "expr": "svd_http_success_counter{service=\"digit-dgepu-service\"}",
     "legendFormat": "Успешные запросы"
    },
    {
     "expr": "svd_http_failure_counter{service=\"digit-dgepu-service\"}",
     "legendFormat": "Неуспешные запросы"
    }
   ]
  },
  {
   "title": "Среднее время обработки HTTP запроса",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(svd_requests_seconds_sum{service=\"digit-dgepu-service\"}) / sum(svd_requests_seconds_count{service=\"digit-dgepu-service\"})",
     "legendFormat": "Среднее t обработки"
    }
   ]
  },
  {
   "title": "Неуспешные запросы",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(svd_http_failure_counter) / sum(svd_http_counter{service=\"digit-dgepu-service\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "PostgreSQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Версия",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_static{service=\"digit-postgres-exporter\"}",
     "legendFormat": "{{short_version}}"
    }
   ]
  },
  {
   "title": "Среднее использование процессора",
   "type": "timeseries",
   "description": "Среднее время работы процессора пользователя и системы в секундах.",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{service=\"digit-postgres-exporter\"}[5m]) * 1000)",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "Среднее использование памяти",
   "type": "timeseries",
   "description": "Размер виртуальной и резидентной памяти в байтах, средние значения за интервал 5 минут",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes{service=\"digit-postgres-exporter\"}[5m]))",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "avg(rate(process_virtual_memory_bytes{service=\"digit-postgres-exporter\"}[5m]))",
     "legendFormat": "Virtual Mem"
    }
   ]
  },
  {
   "title": "Текущие данные выборки",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_fetched{datname=~\"dgcore_gar|meas_params\", service=\"digit-postgres-exporter\"})"
    }
   ]
  },
  {
   "title": "Текущие данные вставки",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_inserted{service=\"digit-postgres-exporter\", datname=~\"meas_params|dgcore_gar\"})"
    }
   ]
  },
  {
   "title": "Текущие данные обновления",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_updated{service=\"digit-postgres-exporter\", datname=~\"meas_params|dgcore_gar\"})"
    }
   ]
  },
  {
   "title": "Активные сессии",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=~\"$database\", service=\"digit-postgres-exporter\", state=\"active\"} !=0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Транзакции",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_commit{service=\"digit-postgres-exporter\", datname=~\"$database\"}[5m])",
     "legendFormat": "{{datname}} commits"
    },
    {
     "expr": "irate(pg_stat_database_xact_rollback{service=\"digit-postgres-exporter\", datname=~\"$database\"}[5m])",
     "legendFormat": "{{datname}} rollbacks"
    }
   ]
  },
  {
   "title": "Выборка данных",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_stat_database_tup_fetched{service=\"digit-postgres-exporter\", datname=~\"$database\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Вставка данных",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_stat_database_tup_inserted{service=\"digit-postgres-exporter\", datname=~\"$database\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Обновление данных",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_stat_database_tup_updated{service=\"digit-postgres-exporter\", datname=~\"$database\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  { "title": "Cassandra", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Всего нод",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cassandra_stats{cluster=~\"$cluster\", datacenter=~\"$datacenter\", name=\"org:apache:cassandra:net:failuredetector:upendpointcount\"})"
    }
   ]
  },
  {
   "title": "Клиентские подключения",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 5, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cassandra_stats{cluster=~\"$cluster\", datacenter=~\"$datacenter\", name=\"org:apache:cassandra:metrics:client:connectednativeclients:value\"})"
    }
   ]
  },
  {
   "title": "Операции по экземпляру",
   "type": "timeseries",
   "description": "Запросы, обслуживаемые каждым экземпляром кластера",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "label_replace(sum by(instance) (cassandra_stats{cluster=\"$cluster\", datacenter=~\"$datacenter\", name=~\"org:apache:cassandra:metrics:clientrequest:(read|write|casread|caswrite|rangeslice|viewwrite):latency:oneminuterate\"}), \"short_instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_instance}}"
    }
   ]
  },
  {
   "title": "Отключенные ноды",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cassandra_stats{cluster=~\"$cluster\", datacenter=~\"$datacenter\", name=\"org:apache:cassandra:net:failuredetector:downendpointcount\"})"
    }
   ]
  },
  {
   "title": "OPS по кластеру",
   "type": "timeseries",
   "description": "Общее количество агрегированных запросов в секунду по кластерам",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(cassandra_stats{cluster=\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:clientrequest:(read|write|casread|caswrite|rangeslice|viewwrite):latency:oneminuterate\"})",
     "legendFormat": "All"
    },
    {
     "expr": "sum(cassandra_stats{cluster=\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:clientrequest:read:latency:oneminuterate\"})",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(cassandra_stats{cluster=\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:clientrequest:write:latency:oneminuterate\"})",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(cassandra_stats{cluster=\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:clientrequest:casread:latency:oneminuterate\"})",
     "legendFormat": "CasRead"
    },
    {
     "expr": "sum(cassandra_stats{cluster=\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:clientrequest:caswrite:latency:oneminuterate\"})",
     "legendFormat": "CasWrite"
    },
    {
     "expr": "sum(cassandra_stats{cluster=\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:clientrequest:rangeslice:latency:oneminuterate\"})",
     "legendFormat": "RangeSlice"
    },
    {
     "expr": "sum(cassandra_stats{cluster=\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:clientrequest:viewwrite:latency:oneminuterate\"})",
     "legendFormat": "ViewWrite"
    }
   ]
  },
  {
   "title": "Операции записи",
   "type": "timeseries",
   "description": "Операции записи по экземпляру",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "label_replace(sum(cassandra_stats{cluster=\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:clientrequest:write:latency:oneminuterate\"}+0.00000001) by (instance),\"short_instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_instance}}"
    }
   ]
  },
  {
   "title": "Операции чтения",
   "type": "timeseries",
   "description": "Операции чтения по экземпляру",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "label_replace(sum(cassandra_stats{cluster=\"$cluster\",datacenter=~\"$datacenter\",instance=~\".*\",name=~\"org:apache:cassandra:metrics:clientrequest:read:latency:oneminuterate\"}+0.00000001) by (instance),\"short_instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_instance}}"
    }
   ]
  },
  {
   "title": "Количество ошибок",
   "type": "timeseries",
   "description": "Возникаемые исключения по экземпляру",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(cassandra_stats{cluster=\"$cluster\",datacenter=~\"$datacenter\",instance=~\".+\",name=~\"org:apache:cassandra:metrics:storage:exceptions:count\"},\"short_instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_instance}}"
    }
   ]
  },
  {
   "title": "Всего таймаутов подключения",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(cassandra_stats{cluster=\"$cluster\",datacenter=~\"$datacenter\",instance=~\".+\",job=~\".+\",name=\"org:apache:cassandra:metrics:connection:totaltimeouts:oneminuterate\"})",
     "legendFormat": "ctt"
    }
   ]
  }
 ]
}