apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: digit-svd-control-data-pvc
  namespace: digit
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: localpath
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: Service
metadata:
  name: digit-svd-control-service
  namespace: digit
spec:
  selector:
    app: digit-svd-control
  ports:
    - protocol: UDP
      port: 11000
      targetPort: 11000

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: digit-svd-control-config
  namespace: digit
data:
  config.json: |
    {
      "appAddr": "http://172.21.100.57:8080/pros",
      "appUser": "rest",
      "appPswd": "rest",
      "socket": "11000",
      "Default": {
        "debugLevel": 9,
        "mainLoopDelay": 5,
        "sessionDelayBegin": 1,
        "sessionDelayExit": 5,
        "sessionSyncPeriod": 10,
        "sessionSafeKeeping": 60,
        "sessionLifeTime": 60
      },
      "SVD": [
        {
          "code": "simple",
          "image": "85.141.97.224:443/svd_simple:4.5.2.0",
          "socket": "10101"
        },
        {
          "code": "mqtt",
          "image": "85.141.97.224:443/svd_simple:4.5.2.0",
          "socket": "10102"
        },
        {
          "code": "opcua",
          "image": "85.141.97.224:443/svd_simple:4.5.2.0",
          "socket": "10103"
        },
        {
          "code": "adm",
          "image": "85.141.97.224:443/svd_simple:4.5.2.0",
          "socket": "10104"
        },
        {
          "code": "akta",
          "image": "85.141.97.224:443/svd_simple:4.5.2.0",
          "socket": "10105"
        },
        {
          "code": "asduk",
          "image": "85.141.97.224:443/svd_simple:4.5.2.0",
          "socket": "10106"
        },
        {
          "code": "asumontazh",
          "image": "85.141.97.224:443/svd_asumontazh:4.5.2.0",
          "socket": "10107"
        },
        {
          "code": "axikam",
          "image": "85.141.97.224:443/svd_asumontazh:4.5.2.0",
          "socket": "10108"
        },
        {
          "code": "bpekck",
          "image": "85.141.97.224:443/svd_asumontazh:4.5.2.0",
          "socket": "10109"
        },
        {
          "code": "csd_spg740",
          "image": "85.141.97.224:443/svd_asumontazh:4.5.2.0",
          "socket": "10110"
        },
        {
          "code": "csd_stel",
          "image": "85.141.97.224:443/svd_asumontazh:4.5.2.0",
          "socket": "10111"
        },
        {
          "code": "csd_tekon",
          "image": "85.141.97.224:443/svd_asumontazh:4.5.2.0",
          "socket": "10112"
        },
        {
          "code": "csd_tekon_iec870",
          "image": "85.141.97.224:443/svd_csd_tekon_iec870:4.5.2.0",
          "socket": "10116"
        },
        {
            "code": "csd_ultramag_mbrtu",
            "image": "85.141.97.224:443/svd_csd_ultramag_mbrtu:4.5.2.0",
            "socket": "10117"
        },
        {
            "code": "dlms",
            "image": "85.141.97.224:443/svd_dlms:4.5.2.0",
            "socket": "10118"
        },
        {
            "code": "egts",
            "image": "85.141.97.224:443/svd_egts:4.5.2.0",
            "socket": "10119"
        },
        {
            "code": "electra",
            "image": "85.141.97.224:443/svd_electra:4.5.2.0",
            "socket": "10120"
        },
        {
            "code": "fmb920",
            "image": "85.141.97.224:443/svd_fmb920:4.5.2.0",
            "socket": "10121"
        },
        {
            "code": "ftp_axi",
            "image": "85.141.97.224:443/svd_ftp_axi:4.5.2.0",
            "socket": "10122"
        },
        {
            "code": "fw_axitech",
            "image": "85.141.97.224:443/svd_fw_axitech:4.5.2.0",
            "socket": "10123"
        },
        {
            "code": "fw_elster",
            "image": "85.141.97.224:443/svd_fw_elster:4.5.2.0",
            "socket": "10124"
        },
        {
            "code": "fw_mosgaz",
            "image": "85.141.97.224:443/svd_fw_mosgaz:4.5.2.0",
            "socket": "10125"
        },
        {
            "code": "gazdev",
            "image": "85.141.97.224:443/svd_gazdev:4.5.2.0",
            "socket": "10126"
        },
        {
            "code": "grsysd",
            "image": "85.141.97.224:443/svd_grsysd:4.5.2.0",
            "socket": "10127"
        },
        {
            "code": "gsp",
            "image": "85.141.97.224:443/svd_gsp:4.5.2.0",
            "socket": "10128"
        },
        {
            "code": "impl",
            "image": "85.141.97.224:443/svd_impl:4.5.2.0",
            "socket": "10129"
        },
        {
            "code": "irvis",
            "image": "85.141.97.224:443/svd_irvis:4.5.2.0",
            "socket": "10130"
        },
        {
            "code": "kam25a",
            "image": "85.141.97.224:443/svd_kam25a:4.5.2.0",
            "socket": "10131"
        },
        {
            "code": "ksh2",
            "image": "85.141.97.224:443/svd_ksh2:4.5.2.0",
            "socket": "10132"
        },
        {
            "code": "kshb",
            "image": "85.141.97.224:443/svd_kshb:4.5.2.0",
            "socket": "10133"
        },
        {
            "code": "meraq",
            "image": "85.141.97.224:443/svd_meraq:4.5.2.0",
            "socket": "10134"
        },
        {
            "code": "micronica_bbt",
            "image": "85.141.97.224:443/svd_micronica_bbt:4.5.2.0",
            "socket": "10135"
        },
        {
            "code": "micronica",
            "image": "85.141.97.224:443/svd_micronica:4.5.2.0",
            "socket": "10136"
        },
        {
            "code": "micronica_typem",
            "image": "85.141.97.224:443/svd_micronica_typem:4.5.2.0",
            "socket": "10137"
        },
        {
            "code": "mirtek",
            "image": "85.141.97.224:443/svd_mirtek:4.5.2.0",
            "socket": "10138"
        },
        {
            "code": "moscad",
            "image": "85.141.97.224:443/svd_moscad:4.5.2.0",
            "socket": "10139"
        },
        {
            "code": "mqtt_ecwatel",
            "image": "85.141.97.224:443/svd_mqtt_ecwatel:4.5.2.0",
            "socket": "10140"
        },
        {
            "code": "mqtt_kona",
            "image": "85.141.97.224:443/svd_mqtt_kona:4.5.2.0",
            "socket": "10141"
        },
        {
            "code": "mqtt_neo",
            "image": "85.141.97.224:443/svd_mqtt_neo:4.5.2.0",
            "socket": "10142"
        },
        {
            "code": "mqtt_schematech",
            "image": "85.141.97.224:443/svd_mqtt_schematech:4.5.2.0",
            "socket": "10143"
        },
        {
            "code": "mrgt",
            "image": "85.141.97.224:443/svd_mrgt:4.5.2.0",
            "socket": "10144"
        },
        {
            "code": "ntcbflex",
            "image": "85.141.97.224:443/svd_ntcbflex:4.5.2.0",
            "socket": "10145"
        },
        {
            "code": "opcua_mc",
            "image": "85.141.97.224:443/svd_opcua_mc:4.5.2.0",
            "socket": "10146"
        },
        {
            "code": "pulsar",
            "image": "85.141.97.224:443/svd_pulsar:4.5.2.0",
            "socket": "10147"
        },
        {
            "code": "radan",
            "image": "85.141.97.224:443/svd_radan:4.5.2.0",
            "socket": "10148"
        },
        {
            "code": "ssoft5",
            "image": "85.141.97.224:443/svd_ssoft5:4.5.2.0",
            "socket": "10149"
        },
        {
            "code": "ssoft6",
            "image": "85.141.97.224:443/svd_ssoft6:4.5.2.0",
            "socket": "10150"
        },
        {
            "code": "turbodon",
            "image": "85.141.97.224:443/svd_turbodon:4.5.2.0",
            "socket": "10152"
        }
      ]
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: digit-svd-control-deployment
  namespace: digit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digit-svd-control
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: digit-svd-control
    spec:
      serviceAccountName: digit-svd-sa
      imagePullSecrets:
        - name: digit-dgepu-secret
      containers:
        - name: digit-svd-control
          image: 85.141.97.224:443/svd_control:4.10.1
          imagePullPolicy: Always
          ports:
            - containerPort: 11000
              protocol: UDP
          env:
            - name: TZ
              value: "Europe/Moscow"
          volumeMounts:
            - name: digit-svd-control-data-rsc
              mountPath: /svd/host
            - name: config-volume
              mountPath: /svd/host/config.json # Монтируем `config.json` непосредственно в `/svd/host`
              subPath: config.json # Монтируем только файл `config.json`
          # livenessProbe:
          #   exec:
          #     command:
          #     - /bin/sh
          #     - -c
          #     - "exit 0"  # Всегда возвращает успешный статус (код 0)
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          # readinessProbe:
          #   exec:
          #     command:
          #     - /bin/sh
          #     - -c
          #     - "exit 0"  # Всегда возвращает успешный статус (код 0)
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
      volumes:
        - name: digit-svd-control-data-rsc
          persistentVolumeClaim:
            claimName: digit-svd-control-data-pvc
        - name: config-volume
          configMap:
            name: digit-svd-control-config
