apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: digit-svd-csd_ultramag_mbrtu-data-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: localpath
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: digit-svd-csd_ultramag_mbrtu-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digit-svd
      component: csd_ultramag_mbrtu
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: digit-svd
        component: csd_ultramag_mbrtu
    spec:
      serviceAccountName: digit-svd-sa
      imagePullSecrets:
        - name: digit-dgepu-secret
      containers:
      - name: csd_ultramag_mbrtu
        namespace: digit
        image: 85.141.97.224:443/svd_csd_ultramag_mbrtu:4.5.2.0
        ports:
        - containerPort: 10117
        env:
        - name: SVDCode
          value: "csd_ultramag_mbrtu"
        - name: SVDControl
          value: "digit-svd-control-service:11000"
        - name: TZ
          value: "Europe/Moscow"
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
          - name: digit-svd-csd_ultramag_mbrtu-data-rsc
            mountPath: /svd/host
      volumes:
      - name: digit-svd-csd_ultramag_mbrtu-data-rsc
        persistentVolumeClaim:
          claimName: digit-svd-csd_ultramag_mbrtu-data-pvc
