apiVersion: v1
kind: Service
metadata:
  name: digit-cassandra-exporter
  labels:
    prometheus.deckhouse.io/custom-target: digit-cassandra-exporter
  annotations:
    prometheus.deckhouse.io/port: "8890"
    # prometheus.deckhouse.io/path: "/pros/rest/prometheus/metrics"
spec:
  ports:
  - name: metrics
    protocol: TCP
    port: 8890
    targetPort: 8890
  selector:
    app: digit-cassandra-exporter
  type: ClusterIP

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: digit-cassandra-exporter-config
data:
  config.yml: |
    host: digit-cassandra-service:7199
    ssl: False
    user: cassandra
    password: cassandra
    listenPort: 8890
    blacklist:
      # To profile the duration of jmx call you can start the program with the following options
      # > java -Dorg.slf4j.simpleLogger.defaultLogLevel=trace -jar cassandra_exporter.jar config.yml --oneshot
      #
      # To get intuition of what is done by cassandra when something is called you can look in cassandra
      # https://github.com/apache/cassandra/tree/trunk/src/java/org/apache/cassandra/metrics
      # Please avoid to scrape frequently those calls that are iterating over all sstables

      # Unaccessible metrics (not enough privilege)
      - java:lang:memorypool:.*usagethreshold.*

      # Leaf attributes not interesting for us but that are presents in many path
      - .*:999thpercentile
      - .*:95thpercentile
      - .*:fifteenminuterate
      - .*:fiveminuterate
      - .*:durationunit
      - .*:rateunit
      - .*:stddev
      - .*:meanrate
      - .*:mean
      - .*:min

      # Path present in many metrics but uninterresting
      - .*:viewlockacquiretime:.*
      - .*:viewreadtime:.*
      - .*:cas[a-z]+latency:.*
      - .*:colupdatetimedeltahistogram:.*

      # Mostly for RPC, do not scrap them
      - org:apache:cassandra:db:.*

      # columnfamily is an alias for Table metrics
      # https://github.com/apache/cassandra/blob/8b3a60b9a7dbefeecc06bace617279612ec7092d/src/java/org/apache/cassandra/metrics/TableMetrics.java#L162
      - org:apache:cassandra:metrics:columnfamily:.*

      # Should we export metrics for system keyspaces/tables ?
      - org:apache:cassandra:metrics:[^:]+:system[^:]*:.*

      # Don't scrap us
      - com:criteo:nosql:cassandra:exporter:.*

    maxScrapFrequencyInSec:
      50:
        - .*

      # Refresh those metrics only every hour as it is costly for cassandra to retrieve them
      3600:
        - .*:snapshotssize:.*
        - .*:estimated.*
        - .*:totaldiskspaceused:.*

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: digit-cassandra-exporter
  labels:
    app: digit-cassandra-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digit-cassandra-exporter
  template:
    metadata:
      labels:
        app: digit-cassandra-exporter
    spec:
      containers:
      - name: digit-cassandra-exporter
        image: bitnami/cassandra-exporter:latest
        ports:
        - containerPort: 8890
          name: metrics
        volumeMounts:
        - name: config-volume
          mountPath: /opt/bitnami/cassandra-exporter/config.yml
          subPath: config.yml
          readOnly: true
        # env:
        # - name: CASSANDRA_EXPORTER_CONFIG
        #   value: /etc/digit-cassandra-exporter/cassandra.yml
      volumes:
      - name: config-volume
        configMap:
          name: digit-cassandra-exporter-config

