apiVersion: v1
kind: Service
metadata:
  name: digit-kspd-shared-lb
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.222.46.200
  clusterIPs:
  - 10.222.46.200
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31330
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: digit-dgepu
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
