# Генерация манифеста (с неймспейсом)
# kubectl create secret docker-registry digit-dgepu-secret \
#   --namespace=digit \
#   --docker-server=http://85.141.97.224:443 \
#   --docker-username=admin \
#   --docker-password=Metrolog1 \
#   --docker-email=alekslesik@gmail.com \
#   --dry-run=client -o yaml > secret-docker-registry.yaml

apiVersion: v1
kind: Secret
metadata:
  name: digit-dgepu-secret
  namespace: digit
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwOi8vODUuMTQxLjk3LjIyNDo0NDMiOnsidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiTWV0cm9sb2cxIiwiZW1haWwiOiJhbGVrc2xlc2lrQGdtYWlsLmNvbSJ9fX0=
  
# .dockerconfigjson:
# echo -n '{"auths":{"http://85.141.97.224:443":{"username":"admin","password":"Metrolog1","email":"alekslesik@gmail.com"}}}' | base64
