apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: digit-dgepu-data-localpath-pvc
  namespace: digit
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: localpath
  resources:
    requests:
      storage: 50Gi
      
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: digit-dgepu-config-localpath-pvc
  namespace: digit
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: localpath
  resources:
    requests:
      storage: 1Gi
      
---

apiVersion: v1
kind: Service
metadata:
  name: digit-dgepu-service
  namespace: digit
  labels:
    prometheus.deckhouse.io/custom-target: digit-dgepu-service
  annotations:
    prometheus.deckhouse.io/port: "8080"                      # По умолчанию будет использоваться порт сервиса с именем http-metrics или https-metrics.
    prometheus.deckhouse.io/path: "/pros/rest/prometheus/metrics"
spec:
  selector:
    app: digit-dgepu
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: dgepu-config
  namespace: digit
data:
  local.app.properties: |
    #cuba.webHostName=A7D1-WEB-01

    # Использование переменной окружения для хоста базы данных PostgreSQL
    cuba.dataSource.host=${POSTGRES_HOST}
    cuba.dbmsType=postgres
    cuba.dataSource_meas_params.host=${POSTGRES_HOST}
    cuba.dataSource_pros.host=${POSTGRES_HOST}
    cuba.dataSource_gar_fias.host=${POSTGRES_HOST}
    cuba.dataSource_imus_big.host=${POSTGRES_HOST}
    cuba.dataSource_protect_means.host=${POSTGRES_HOST}
    cuba.dataSource_gar.host=${POSTGRES_HOST}
    cuba.dataSource_dgcore_gar.host=${POSTGRES_HOST}

    cuba.automaticDatabaseUpdate=true

    # Использование переменных окружения для логина и пароля PostgreSQL
    cuba.dataSource.username=postgres
    cuba.dataSource.password=postgres

    # Если пароль при установке\подключении отличный от postgres, то нужно везде переопределять эти все свойства
    #cuba.dataSource_imus_big.password=postgres123
    #cuba.dataSource_meas_params.password=postgres123
    #cuba.dataSource_pros.password=postgres123
    #cuba.dataSource_gar_fias.password=postgres123
    #cuba.dataSource_protect_means.password=postgres123

    # Использование переменных окружения для Cassandra
    cass.user=cassandra
    cass.password=cassandra
    cass.nodes=${CASSANDRA_HOST}
    cass.replicationFactor=3
    cass.cassLocalDatacenter=DC1
    
    #cuba.cassandra.contactPoints=digit-cassandra-statefulset-0.digit-cassandra-service.default.svc.cluster.local,digit-cassandra-statefulset-1.digit-cassandra-service.default.svc.cluster.local,digit-cassandra-statefulset-2.digit-cassandra-service.default.svc.cluster.local
    #cass.port=9042

    cuba.bruteForceProtection.enabled=true
    cuba.bruteForceProtection.blockIntervalSec=120
    cuba.bruteForceProtection.maxLoginAttemptsNumber=5
    cuba.web.loginDialogDefaultUser=<disabled>
    cuba.web.loginDialogDefaultPassword=<disabled>
    cuba.web.loginDialogPoweredByLinkVisible=false

    cuba.userSessionExpirationTimeoutSec=86400
    cuba.httpSessionExpirationTimeoutSec=86400

    cuba.availableLocales=Russian|ru

    reporting.office.path=/usr/lib/libreoffice/program

  logback.xml: |
    <?xml version="1.0" encoding="UTF-8"?>

    <configuration debug="false" packagingData="true">

    <property name="logDir" value="${app.home}/logs"/>

    <appender name="File" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <file>${logDir}/app.log</file>

        <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
            <level>INFO</level>
        </filter>

        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            <!-- daily rollover -->
            <fileNamePattern>${logDir}/app.%d{yyyy-MM-dd}.log</fileNamePattern>
            <!-- keep 30 days' worth of history -->
            <maxHistory>30</maxHistory>
            <cleanHistoryOnStart>true</cleanHistoryOnStart>
        </rollingPolicy>

        <encoder>
            <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread%X{cubaApp}%X{cubaUser}] %logger - %msg%n</pattern>
        </encoder>
    </appender>

    <appender name="AdapterFile" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <file>${logDir}/adapter.log</file>

        <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
            <level>INFO</level>
        </filter>

        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            <!-- daily rollover -->
            <fileNamePattern>${logDir}/adapter.%d{yyyy-MM-dd}.log</fileNamePattern>
            <!-- keep 30 days' worth of history -->
            <maxHistory>30</maxHistory>
            <cleanHistoryOnStart>true</cleanHistoryOnStart>
        </rollingPolicy>

        <encoder>
            <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread%X{cubaApp}%X{cubaUser}] %logger - %msg%n</pattern>
        </encoder>
    </appender>

    <appender name="Console" class="ch.qos.logback.core.ConsoleAppender">
        <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
            <level>INFO</level>
        </filter>

        <encoder>
            <pattern>%d{HH:mm:ss.SSS} %-5level %-40logger{36}- %msg%n</pattern>
        </encoder>
    </appender>

    <appender name="SecurityFile" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <file>${logDir}/security.log</file>

        <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
            <level>INFO</level>
        </filter>

        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            <!-- daily rollover -->
            <fileNamePattern>${logDir}/security.%d{yyyy-MM-dd}.log</fileNamePattern>
            <!-- keep 30 days' worth of history -->
            <maxHistory>30</maxHistory>
            <cleanHistoryOnStart>true</cleanHistoryOnStart>
        </rollingPolicy>

        <encoder>
            <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread%X{cubaApp}%X{cubaUser}] %logger - %msg%n</pattern>
        </encoder>
    </appender>

    <appender name="SvdFile" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <file>${logDir}/svd.log</file>

        <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
            <level>INFO</level>
        </filter>

        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            <!-- daily rollover -->
            <fileNamePattern>${logDir}/svd.%d{yyyy-MM-dd}.log</fileNamePattern>
            <!-- keep 30 days' worth of history -->
            <maxHistory>30</maxHistory>
            <cleanHistoryOnStart>true</cleanHistoryOnStart>
        </rollingPolicy>

        <encoder>
            <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread%X{cubaApp}%X{cubaUser}] %logger - %msg%n</pattern>
        </encoder>
    </appender>
  
    <appender name="ConsoleLogs" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <file>${logDir}/app-console.log</file>

        <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
            <level>INFO</level>
        </filter>

        <encoder>
            <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger - %msg%n</pattern>
        </encoder>
    </appender>

    <appender name="TestgenSvdFile" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <file>${logDir}/svd-testgen.log</file>

        <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
            <level>INFO</level>
        </filter>

        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            <!-- daily rollover -->
            <fileNamePattern>${logDir}/svd-testgen.%d{yyyy-MM-dd}.log</fileNamePattern>
            <!-- keep 30 days' worth of history -->
            <maxHistory>30</maxHistory>
            <cleanHistoryOnStart>true</cleanHistoryOnStart>
        </rollingPolicy>

        <encoder>
            <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread%X{cubaApp}%X{cubaUser}] %logger - %msg%n</pattern>
        </encoder>
    </appender>

    <root>
        <appender-ref ref="Console"/>
        <appender-ref ref="File"/>
    </root>

    <!-- Begin CUBA -->

    <logger name="com.haulmont.cuba" level="DEBUG">
      <appender-ref ref="ConsoleLogs"/>
    </logger>

    <logger name="com.haulmont.cuba.core.sys" level="INFO">
      <appender-ref ref="ConsoleLogs"/>
    </logger>

    <logger name="com.haulmont.cuba.core.sys.CubaDefaultListableBeanFactory" level="WARN"/>

    <logger name="com.haulmont.cuba.core.app.scheduling" level="INFO"/>

    <logger name="com.haulmont.cuba.web.sys" level="INFO"/>

    <logger name="com.haulmont.cuba.portal" level="INFO"/>

    <logger name="com.haulmont.restapi.sys" level="INFO">
      <appender-ref ref="ConsoleLogs"/>
    </logger>

    <logger name="com.haulmont.cuba.core.app.LockManager" level="INFO"/>

    <!-- End CUBA -->

    <logger name="eclipselink" level="WARN"/>

    <logger name="eclipselink.sql" level="INFO"/>

    <logger name="org.springframework" level="WARN">
      <appender-ref ref="ConsoleLogs"/>
    </logger>

    <logger name="com.vaadin" level="WARN"/>

    <logger name="org.atmosphere" level="WARN"/>

    <logger name="org.activiti" level="INFO"/>

    <logger name="org.jgroups" level="INFO"/>

    <logger name="freemarker" level="INFO"/>

    <logger name="org.thymeleaf.TemplateEngine" level="INFO"/>

    <logger name="com.zaxxer.hikari" level="INFO"/>

    <logger name="org.docx4j" level="WARN"/>

    <logger name="org.xlsx4j" level="WARN"/>

    <logger name="org.apache.fop.apps.FOUserAgent" level="WARN"/>

    <logger name="org.hibernate" level="WARN"/>

    <logger name="sun" level="INFO"/>

    <logger name="com.sun" level="INFO"/>

    <logger name="javax" level="INFO"/>

    <logger name="org.apache" level="INFO"/>

    <logger name="org.eclipse.jetty" level="INFO">
      <appender-ref ref="ConsoleLogs"/>
    </logger>

    <logger name="org.docx4j.utils.ResourceUtils" level="ERROR"/>

    <logger name="org.docx4j.Docx4jProperties" level="ERROR"/>

    <logger name="org.xlsx4j.jaxb.Context" level="ERROR"/>

    <logger name="org.docx4j.utils.XSLTUtils" level="ERROR"/>

    <logger name="org.docx4j.jaxb.JaxbValidationEventHandler" level="ERROR"/>

    <logger name="org.docx4j.TraversalUtil" level="ERROR"/>

    <logger name="org.docx4j.fonts" level="ERROR"/>

    <!-- Begin Perf4J  -->

    <appender name="PerfStatFile" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <file>${logDir}/perfstat.log</file>
        <append>true</append>

        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            <fileNamePattern>${logDir}/perfstat.%d{yyyy-MM-dd}.log</fileNamePattern>
            <maxHistory>30</maxHistory>
            <cleanHistoryOnStart>true</cleanHistoryOnStart>
        </rollingPolicy>

        <encoder>
            <pattern>%msg%n</pattern>
        </encoder>
    </appender>

    <appender name="CoalescingStatistics" class="org.perf4j.logback.AsyncCoalescingStatisticsAppender">
        <param name="TimeSlice" value="60000"/>
        <appender-ref ref="PerfStatFile"/>
    </appender>

    <appender name="UIPerfStatFile" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <file>${logDir}/perfstat-ui.log</file>
        <append>true</append>

        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            <fileNamePattern>${logDir}/perfstat-ui.%d{yyyy-MM-dd}.log</fileNamePattern>
            <maxHistory>30</maxHistory>
            <cleanHistoryOnStart>true</cleanHistoryOnStart>
        </rollingPolicy>

        <encoder>
            <pattern>%msg%n</pattern>
        </encoder>
    </appender>

    <appender name="UICoalescingStatistics" class="org.perf4j.logback.AsyncCoalescingStatisticsAppender">
        <param name="TimeSlice" value="120000"/>
        <appender-ref ref="UIPerfStatFile"/>
    </appender>

    <logger name="org.perf4j.TimingLogger" additivity="false" level="INFO">
        <appender-ref ref="CoalescingStatistics"/>
    </logger>

    <logger name="com.haulmont.cuba.gui.logging.UIPerformanceLogger" additivity="false" level="INFO">
        <appender-ref ref="UICoalescingStatistics"/>
    </logger>

    <logger name="service.all.security" additivity="false" level="INFO">
        <appender-ref ref="Console"/>
        <appender-ref ref="SecurityFile"/>
    </logger>

    <logger name="service.testgen.MpService" additivity="false" level="INFO">
        <appender-ref ref="Console"/>
        <appender-ref ref="TestgenSvdFile"/>
    </logger>

    <logger name="service" additivity="false" level="INFO">
        <appender-ref ref="Console"/>
        <appender-ref ref="SvdFile"/>
    </logger>

    <logger name="MpdAdapter(svd_rgkspb_mpd)" additivity="false" level="INFO">
        <appender-ref ref="AdapterFile"/>
    </logger>

    <logger name="GazSetShluz(any)" additivity="false" level="INFO">
        <appender-ref ref="AdapterFile"/>
    </logger>

    <!-- End Perf4J  -->

    </configuration>

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: digit-dgepu-deployment
  namespace: digit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digit-dgepu
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: digit-dgepu
    spec:
      imagePullSecrets:
        - name: digit-dgepu-secret
      initContainers:
      - name: copy-config
        image: 85.141.97.224:443/busybox:latest
        command: ['sh', '-c', 'cp /config/* /opt/app_home/']
        volumeMounts:
        - name: config-volume
          mountPath: /config
        - name: digit-dgepu-config-localpath
          mountPath: /opt/app_home
      containers:
      - name: digit-dgepu
        image: 85.141.97.224:443/digit_dgepu:latest
        # imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: CONTAINER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: XMS
          value: "-Xms10000m"
        - name: XMX
          value: "-Xmx20000m"
        - name: JAR
          value: "dgepu.jar"
        - name: TZ
          value: "Europe/Moscow"
        - name: CASSANDRA_HOST
          value: "digit-cassandra-service"
        - name: POSTGRES_HOST
          value: "digit-postgres-headless"
        volumeMounts:
        - name: digit-dgepu-config-localpath
          mountPath: /opt/app_home
        - name: digit-dgepu-data-localpath
          mountPath: /var/lib/dgepu/data
          subPath: data
        startupProbe:
          httpGet:
            path: /pros/
            port: 8080
          failureThreshold: 50
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /pros/
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
      volumes:
      - name: config-volume
        configMap:
          name: dgepu-config
      - name: digit-dgepu-data-localpath
        persistentVolumeClaim:
          claimName: digit-dgepu-data-localpath-pvc
      - name: digit-dgepu-config-localpath
        persistentVolumeClaim:
          claimName: digit-dgepu-config-localpath-pvc
