apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: digit-svd-simple-data-pvc
  namespace: digit
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: replicated-storage-class
  resources:
    requests:
      storage: 20Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: digit-svd-simple-deployment
  namespace: digit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digit-svd
      component: simple
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: digit-svd
        component: simple
    spec:
      serviceAccountName: digit-svd-simple-sa  # Назначаем новый ServiceAccount
      imagePullSecrets:
        - name: digit-dgepu-secret
      containers:
      - name: simple
        image: 85.141.97.224:443/svd_simple:load
        # imagePullPolicy: Always
        ports:
        - containerPort: 10101
        - containerPort: 8889
        env:
        - name: SVDCode
          value: "simple"
        - name: SVDControl
          value: "digit-svd-control-service:11000"
        - name: SVDSocket
          value: "10101"
        # - name: EXCHANGE
        #   value: "rest:rest@http://digit-dgepu-service.default.svc.cluster.local/pros"
        - name: TZ
          value: "Europe/Moscow"
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace  # Автоматическое указание текущего namespace
        volumeMounts:
          - name: digit-svd-simple-data-rsc
            mountPath: /svd/host
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "exit 0"  # Всегда возвращает успешный статус (код 0)
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "exit 0"  # Всегда возвращает успешный статус (код 0)
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: digit-svd-simple-data-rsc
        persistentVolumeClaim:
          claimName: digit-svd-simple-data-pvc
          
