apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: digit-svd-simple-data-pvc
  namespace: digit
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: replicated-storage-class
  resources:
    requests:
      storage: 10Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: digit-svd-fw-elster-deployment
  namespace: digit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digit-svd
      component: fw-elster
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: digit-svd
        component: fw-elster
    spec:
      serviceAccountName: digit-svd-sa
      imagePullSecrets:
        - name: digit-dgepu-secret
      containers:
      - name: fw-elster
        
        image: 85.141.97.224:443/svd_fw_elster:4.8.2.0k
        ports:
        - containerPort: 10124
        env:
        - name: SVDCode
          value: "fw_elster"
        - name: SVDControl
          value: "digit-svd-control-service:11000"
        - name: TZ
          value: "Europe/Moscow"
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
          - name: digit-svd-fw-elster-data-rsc
            mountPath: /svd/host
      volumes:
      - name: digit-svd-fw-elster-data-rsc
        persistentVolumeClaim:
          claimName: digit-svd-fw-elster-data-pvc
